StatsVC layout improvements for dynamic type
ApturiCOVID/apturicovid-ios pull request #10
Opened 2020-07-23 08:56 UTC by MelanijaGrunte

Includes DIG-570 and DIG-571

2020-07-23 10:32 UTC, ULazdins commented on apturicovid/viewController/StatsVC.swift
> +        }
Add else here please

2020-07-23 10:32 UTC, ULazdins commented on apturicovid/viewController/StatsVC.swift
> +            let height = titleLabelSize.height + header.titleLabelTopConstraint.constant + descriptionLabelSize.height + header.descriptionLabelTopConstraint.constant
Can't we use autolayout here?

2020-07-23 12:05 UTC, MelanijaGrunte commented on apturicovid/viewController/StatsVC.swift
> +                                                      verticalFittingPriority: .fittingSizeLevel)
@ULazdins UICollectionView's auto-layout can be achieved through code only. I've updated the method.

2020-07-23 12:08 UTC, ULazdins approved these changes

2020-07-24 10:09 UTC, ArtSp commented
Unable to simultaneously satisfy constraints in collection header view.

2020-07-24 10:11 UTC, ArtSp commented
Collection view footer is not scaling.

2020-07-24 10:20 UTC, ArtSp requested changes
- Unable to simultaneously satisfy constraints in collection header view.

- Collection view footer is not scaling

- Collection view doesn't reload when text scale changes. 

- Single row layout must be implemented only for accessibility scales. Display zoom must not be used to determine row count , Plus size phones have full lot of space even with zoomed screen. 

- Cell title label has no top/bottom constraints. With max accessibility scales text height ~= superview height. Can use ~ >=8pt constraints.

- It's better to embed cell value description and value labels into UIStackViews. For larger accessibility fonts you can use vertical axis, and use horizontal for others. Otherwise on SE screen every label has it's own font size, as they all try to fit width. 

- Use `superView.backgroundColor = welcomeHeaderView.fillColor` when collection view content height > than welcomeHeaderView height. Previously this was used only for SE 1gen screens. 

- Align cell value description labels leading anchor to cell description label's leading anchor.

- Adjust cell size to font scale.

2020-07-24 14:43 UTC, mzibara commented on apturicovid/viewController/StatsVC.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(preferredContentSizeChanged(_:)), name: UIContentSizeCategory.didChangeNotification, object: nil)
Couldn't we do this with rxcocoa as well?

2020-07-27 07:09 UTC, ArtSp commented on apturicovid/viewController/StatsVC.swift
> +            .subscribe(onNext: { [weak self] (_) in
Add .observeOn(MainScheduler.instance) so there will be no need to call DispatchQueue.main in preferredContentSizeChanged()

2020-07-27 12:27 UTC, ArtSp approved these changes

2020-07-27 12:32 UTC, merged